Parameters:
  MyBucketName:
    Description: Existing Bucket Name
    Type: String

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicRead
      BucketName: !Sub ${MyBucketName} 
      WebsiteConfiguration: 
        IndexDocument: index.html
        ErrorDocument: error.html

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*" 
            Action: s3.GetObject
            Resource: !Join ['',['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]