resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: main-test-key
      ImageId: 'ami-09e67e426f25ce0d7'
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
  
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: '22'
          ToPort: '22'
      SecurityGroupEgress:
        - Security Group Rule
      Tags:
        - Key:
          Value: