version: 2.1

default: &python-image
  docker:
      - image: cimg/python:3.10.5

jobs:
  Build_and_Test:
    <<: *python-image
    steps:
      - checkout
      - restore_cache:
          key: v1-python-cache-{{ checksum "requirements.txt" }}
      - run:
          name: Create Environment
          command: |
              #create execution environment
              python3 -m venv ~/.django_env
              #activate environment
              source ~/.django_env/bin/activate
      - run:
          name: Build Environment
          command: |
              cd myproject
              python3 -m pip install -r requirements.txt
      - run:
          name: Test Account App
          command: |
            pwd
            cd myproject
            python manage.py test accounts/tests
      - run:
          name: Test Board App
          command: |
            python manage.py test board/tests
      - save_cache:
          paths:
            - ~/.django_env 
          key: v1-python-cache-{{ checksum "requirements.txt" }} 

      
  # Test_Environment:
  #   <<: *python-image
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         key: v1-python-cache-{{ checksum "requirements.txt" }}
  #     - run: source ~/.django_env/bin/activate
      
  
  
workflows:
  test_codes:
    jobs:
      - Build_and_Test