version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  create-infrastructure:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION_NAME
      - run:
          name: Create cloudformation stack
          command: |
            aws cloudformation deploy --template-file template.yml --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
            --region us-east-1

workflows:
  createin-frastructure:
    jobs:
      - create-infrastructure      
